<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1hbtln7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1hbtln7/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1hbtln7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1hbtln7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1hbtln7\appProdProjectContainer(array(
    'container.build_hash' => '1hbtln7',
    'container.build_id' => '55f281b5',
    'container.build_time' => 1551718499,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1hbtln7');
