<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsxpywu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsxpywu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIsxpywu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIsxpywu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIsxpywu\appProdProjectContainer(array(
    'container.build_hash' => 'Isxpywu',
    'container.build_id' => '7805cb4c',
    'container.build_time' => 1548956209,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsxpywu');
