<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsakjuz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsakjuz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWsakjuz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWsakjuz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWsakjuz\appProdProjectContainer(array(
    'container.build_hash' => 'Wsakjuz',
    'container.build_id' => 'ffb55a1e',
    'container.build_time' => 1548941799,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsakjuz');
