<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUcygbda\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUcygbda/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUcygbda.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUcygbda\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUcygbda\appProdProjectContainer(array(
    'container.build_hash' => 'Ucygbda',
    'container.build_id' => '7ad0e2e7',
    'container.build_time' => 1545321635,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUcygbda');
