<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6pwhxxa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6pwhxxa/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6pwhxxa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6pwhxxa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6pwhxxa\appProdProjectContainer(array(
    'container.build_hash' => '6pwhxxa',
    'container.build_id' => '12a7118b',
    'container.build_time' => 1545840080,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6pwhxxa');
