jeremy_produit_homepage:
    path:     /
    defaults: { _controller: JeremyProduitBundle:Default:index }

jeremy_produit_ajouter:
    path: /action=ajouter
    defaults: { _controller: JeremyProduitBundle:Default:ajouter }

jeremy_produit_modifier:
  path: /action=modif{id_du_produit}
  defaults:
    _controller: JeremyProduitBundle:Default:modifierProduit
  requirements:
    id_de_auteur: '\d+' # d = 0-9 / d+ = 0 à l'infini

jeremy_produit_supprimer:
  path: /action=suppr{id_du_produit}
  defaults:
    _controller: JeremyProduitBundle:Default:supprimerProduit
  requirements:
    id_de_auteur: '\d+' # d = 0-9 / d+ = 0 à l'infini
