jeremy_produit_homepage:
    path:     /
    defaults: { _controller: JeremyProduitBundle:Default:index }

jeremy_produit_ajouter:
    path: /ajouter
    defaults: { _controller: JeremyProduitBundle:Default:ajouter }

jeremy_ifocop_default_modifier_auteur:
  path: /modifier/{id_du_produit}
  defaults:
    _controller: JeremyProduitBundle:Default:modifierProduit
  requirements:
    id_de_auteur: '\d+' # d = 0-9 / d+ = 0 à l'infini
