jeremy_commande_homepage:
    path:     /backoffice=commande
    defaults: { _controller: JeremyCommandeBundle:Default:index }

jeremy_commande_supprimer:
  path: /backoffice=commande/action=suppr{id_commande}
  defaults:
    _controller: JeremyCommandeBundle:Default:supprimerCommande
  requirements:
    id_commande: '\d+' # d = 0-9 / d+ = 0 à l'infini

jeremy_commande_modifier:
  path: /backoffice=commande/action=modif{id_commande}
  defaults:
    _controller: JeremyCommandeBundle:Default:modifierCommande
  requirements:
    id_commande: '\d+' # d = 0-9 / d+ = 0 à l'infini
