<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1bts140\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1bts140/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1bts140.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1bts140\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1bts140\appDevDebugProjectContainer(array(
    'container.build_hash' => '1bts140',
    'container.build_id' => 'd42d115a',
    'container.build_time' => 1551786491,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1bts140');
