<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhtgojn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhtgojn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXhtgojn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXhtgojn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXhtgojn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xhtgojn',
    'container.build_id' => '9f636fce',
    'container.build_time' => 1545594283,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhtgojn');
